spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test?createDatabaseIfNotExist=true
    username: postgres
    password: 1qaz2wsx
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
  batch:
    initialize-schema: ALWAYS