security:
  oauth2:
    client:
      client-id: web
      client-secret: webpass
      user-authorization-uri: http://localhost:9090/oauth/authorize
      access-token-uri: http://localhost:9090/oauth/token
    resource:
      token-info-uri: http://localhost:9090/oauth/check_token
server:
  port: 8281
  servlet:
    session:
      cookie:
        name: BSESSION
